version: 0.2

batch:
  fast-fail: false
  build-fanout:
    parallelism: 5

phases:
  install:
    commands:
      - echo 'Installing Python dependencies' || true
      - export $(grep -v '^#' /etc/environment  | xargs) || true
      - sudo yum install -y python3 python3-pip  || true
      - python3 -m ensurepip --upgrade  || true
      - python3 -m pip install django || true
      - python3 -m pip install -r requirements.txt || true
      
  pre_build:
    commands:
      - echo 'Prebuild'
  build:
    commands:
      - echo 'Running Django'
  post_build:
    commands:
      - echo 'Test execution completed'

artifacts:
  files:
    - '**/*'
    - run.log